version: '3'
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb2
    ports:
      - '8086:8086'
    volumes:
      - ./data/influx_data:/var/lib/influxdb2
      - ./data/influx_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=indhuge
      - DOCKER_INFLUXDB_INIT_PASSWORD=indhuge123
      - DOCKER_INFLUXDB_INIT_ORG=indhuge
      - DOCKER_INFLUXDB_INIT_BUCKET=indehuge-poc
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/posgres:/var/lib/postgresql/data
