on:
  push:
    branches:
    - hmg
  workflow_dispatch:
jobs:
  build_deploy_image:
    name: Build and Deploy to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@hmg

      - name: Setup Docker credentials
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker-compose build

      - name: Deploy
        run: |
          docker-compose push
  deploy_hmg:
    name: Deploy on HMG
    uses: ./.github/workflows/deploy_on_ec2.yml
    needs:
      - build_deploy_image
    secrets: inherit

