on:
  workflow_call:
    secrets:
      ssh_private_key:
        description: 'SSH private key'
        required: true
      ec2_public_ip:
        description: 'EC2 public IP'
        required: true
      docker_user:
        description: 'Docker username'
        required: true
      docker_password:
        description: 'Docker password'
        required: true

jobs:
  deploy_on_ec2:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.ssh_private_key }}
      EC2_PUBLIC_IP: ${{ secrets.ec2_public_ip }}
      DOCKER_USER: ${{ secrets.docker_user }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}
    steps:
    - name: Connect to EC2
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${EC2_PUBLIC_IP} '
          sudo docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          cd indhuge-backend/prod
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d'
